const cors = require('cors');
const express = require('express');
const fs = require('fs');
const path = require('path');
const swaggerUi = require('swagger-ui-express');
const swaggerSpec = require('../swagger');
const { errorHandler } = require('./middleware/errorHandler');

// Initialize express app
const app = express();

// CORS
app.use(cors({
  origin: '*',
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization']
}));
app.set('trust proxy', true);

// Serve raw OpenAPI JSON (generated by swagger-jsdoc) at /openapi.json for compatibility
app.get('/openapi.json', (req, res) => {
  const host = req.get('host');
  const protocol = req.secure ? 'https' : req.protocol;
  const actualPort = req.socket.localPort;
  const hasPort = host.includes(':');
  const needsPort =
    !hasPort &&
    ((protocol === 'http' && actualPort !== 80) ||
     (protocol === 'https' && actualPort !== 443));
  const fullHost = needsPort ? `${host}:${actualPort}` : host;

  const dynamicSpec = {
    ...swaggerSpec,
    servers: [{ url: `${protocol}://${fullHost}` }],
  };
  res.json(dynamicSpec);
});

// Optional: also serve the maintained spec file from interfaces if needed
app.get('/interfaces/openapi.yaml', (req, res) => {
  const p = path.join(__dirname, '..', 'interfaces', 'openapi.yaml');
  if (fs.existsSync(p)) {
    res.setHeader('Content-Type', 'application/yaml');
    res.send(fs.readFileSync(p, 'utf8'));
  } else {
    res.status(404).send('openapi.yaml not found');
  }
});

// Swagger UI with dynamic server using the JSON spec endpoint
app.use('/docs', swaggerUi.serve, swaggerUi.setup(undefined, {
  swaggerUrl: '/openapi.json'
}));

// JSON parser
app.use(express.json());

// Mount routes
app.use('/', require('./routes/health'));
app.use('/api/auth', require('./routes/auth'));
app.use('/api', require('./routes/bank'));

// Unified error handling
app.use(errorHandler);

module.exports = app;
